pipeline {
    agent {
        docker {
            image 'maven:3.5.2-alpine@sha256:cdac1580d86ac7a1ba401030a1917ae55aeba0efb20b8e262822d14955821ed6'
            args '-v /root/.m2:/root/.m2'            
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
